@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "GSM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to add a new entry to the To-Do List
    activate System

        System --> Employee : shows green spaces to select
    deactivate System

    Employee -> System : selects green space
    activate System

        System --> Employee : requests data (description,executionStartDate,executionEndDate)
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml