@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) US021

autonumber

actor "GSM" as Employee
participant ":System" as System
activate Employee

    Employee -> System : asks to add a new entry to the To-Do List
    activate System

        System --> Employee : shows green spaces and task urgency to be selected\n and requests data (taskTitle, taskDescription, expectedDuration)
    deactivate System

    Employee -> System : selects green space and task urgency\n and types requested data
    activate System

        System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml