@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0


class TasksAssignedToMeBetweenTwoDatesUI {

}


class TasksAssignedToMeBetweenToDatesController {


    +getTasks(LocalDate startDate, LocalDate endDate, TaskStatus taskStatus)

}

class Repositories {
    -Repositories()
    +getInstance()
    +getEmployeeRepository()
}

class EmployeeRepository {

}

class Task {
    -status : TaskStatus
    -startDate : LocalDate
    -endDate: LocalDate
    -collaborator: Collaborator
    +getAssignedTeam
    +getTeamEmployees
    +isBetweenDates(LocalDate startDate, LocalDate endDate)
    +isAssignedToCurrentCollaborator()
}

enum TaskStatus {
    PLANNED
    POSTPONED
    CANCELED
    DONE
    PENDING
}

class Employee {
}

TasksAssignedToMeBetweenTwoDatesUI "1" ..> "1" TasksAssignedToMeBetweenToDatesController
TasksAssignedToMeBetweenToDatesController "1" ..> "1" Repositories: repositories

TasksAssignedToMeBetweenToDatesController "1" .> "*" Employee
TasksAssignedToMeBetweenToDatesController "1" .> "*" TaskStatus: taskStatus
Repositories --> Repositories: instance
Repositories "1" --> "1" EmployeeRepository
EmployeeRepository "1" --> "*" Employee
Employee "1" --> "*" Task
Task "1" .> "1" TaskStatus


@enduml