@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto
skinparam classAttributeIconSize 0

'left to right direction


class RegisterGreenSpaceUI {

}

class RegisterGreenSpaceController {
    + getEmployeeRepository() : employeeRepository
    + registerGreenSpace(name: String, address: String, area: double, typology : String, greenSpaceManager: String) : Optional<GreenSpace>
    + existsGreenSpace(name : String) : Boolean

}

class Repositories {
     - Repositories()
     + getInstance() : Repositories
     + getEmployeeRepository() : employeeRepository

}

class Employee {
    -name : String
    -birthdate : Date
    -email : String
    -phoneNumber : int
    -admission date : Date
    -taxpayerNumber : String
    -address : String
    -docNumber : String
    -jobTitle : String
    +registerGreenSpace(name: String, address: String, area: double, typology : String, greenSpaceManager: String) : Optional<GreenSpace>
    +addGreenSpace(greenSpace) : boolean
    +validateGreenSPace(greenSpace) : boolean

}

class EmployeeRepository {
    +getEmployee() : employee
}



class GreenSpace {
        -name : String
        -address : String
        -area : double
        -typology : String
        - greenSpaceManager : String
}





RegisterGreenSpaceController ..> Repositories: repositories
RegisterGreenSpaceController ..> Employee
RegisterGreenSpaceUI .> RegisterGreenSpaceController
Repositories -> Repositories : instance
EmployeeRepository "1" --> "*" Employee
Employee "1" --> "*" GreenSpace : registerGreenSpace
Repositories "1" --> "1" EmployeeRepository



@enduml