@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class RegisterGreenSpaceUI {

}

class RegisterGreenSpaceController {
    + initialize~(): void
    + getEmployeeRepository() : employeeRepository
    + getAuthRepository() : authenticationRepository
    + getGreenSpaceByName() : List<GreenSpace>
    + existsWithAddress(address : String) : boolean
    + existsWithName(name : String) : boolean
    + currentUserLogInValidation() : boolean
    + matchEmployeeByRole() : Employee
    + registerGreenSpace(name: String, address: String, area: double, typology : String, greenSpaceManager: String) : Optional<GreenSpace>

}

class Repositories {
     - Repositories()
     + getInstance() : Repositories
     + getEmployeeRepository() : employeeRepository
     + getAuthRepository() : authenticationRepository

}

class Employee {
    -name : String
    -birthdate : Date
    -email : String
    -phoneNumber : int
    -admission date : Date
    -taxpayerNumber : String
    -address : String
    -docNumber : String
    -jobTitle : String
    +registerGreenSpace(name: String, address: String, area: double, typology : String, greenSpaceManager: String) : Optional<GreenSpace>
    +addGreenSpace(greenSpace) : Optional<GreenSpace>
    +validateGreenSpace(greenSpace) : boolean

}

class EmployeeRepository {
    +getEmployee() : employee
}

class AuthenticationRepository {
    +getCurrentUserSession() : UserSession
}

class GreenSpace {
        -name : String
        -address : String
        -area : double
        -typology : String
        - greenSpaceManager : String
}





RegisterGreenSpaceController ..> Repositories: repositories
RegisterGreenSpaceController ..> Employee
RegisterGreenSpaceUI .> RegisterGreenSpaceController
Repositories -> Repositories : instance
EmployeeRepository "1" --> "*" Employee
AuthenticationRepository "1" --> "*" Employee
Employee "1" --> "*" GreenSpace : registerGreenSpace
Repositories "1" --> "1" EmployeeRepository
Repositories "1" --> "1" AuthenticationRepository




@enduml