@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto
skinparam classAttributeIconSize 0

'left to right direction


class RegisterGreenSpaceUI {

}

class RegisterGreenSpaceController {

    + registerGreenSpace(name: String, address: String, area: double, typology : String, greenSpaceManager: String)
    + existsGreenSpace(name : String) : Boolean
    + getGreenSpaceRepository() : GreenSpaceRepository
    + getAuthRepository() : AuthRepository
    + getEmployeeRepository() : GreenSpaceRepository
    + currentUserLogInValidation : boolean
    + matchEmployeeByRole() : Employee

}

class Repositories {
     - Repositories()
     + getInstance() : Repositories
     + getEmployeeRepository()

}

class Employee {
    name
    birth date
    contact (email/phone)
    admission date
    taxpayer number
    address
    ID doc type and number
    role
}

class EmployeeRepository {
    -employeeList : List<Employee>
    +getEmployee(taxpayerNumber : String) : Optional<Employee>
}



class GreenSpace {
        -name : String
        -address : String
        -area : double
        -typology : String
        - greenSpaceManager : String

    +registerGreenSpace(name: String, address: String, area: double, typology : String, greenSpaceManager: String) : Optional<GreenSpace>
    +GreenSpace()
    +clone() : GreenSpace
    +compareTo(o:GreenSpace) : int
}





RegisterGreenSpaceController ..> Repositories: repositories
RegisterGreenSpaceController ..> Employee
RegisterGreenSpaceUI .> RegisterGreenSpaceController
Repositories -> Repositories : instance
EmployeeRepository "1" --> "*" Employee
Employee "1" --> "*" GreenSpace : register
Repositories "1" --> "1" EmployeeRepository



@enduml