@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as GSM
participant RegisterGreenSpaceUI as UI
participant RegisterGreenSpaceController as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository:\nGreenSpaceRepository" as GreenSpaceRepository
participant "green Space:\nGreen Space" as GREENSPACE
activate GSM

ref over GSM, UI : This action assumes that the user has already logged in

GSM -> UI : asks to register a new green space
activate UI

UI -> GSM : requests typed data
deactivate UI

GSM -> UI : types requested data (name, address, area)
activate UI
UI -> CTRL : getGreenSpaceTypology()
activate CTRL

CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

CTRL -> PLAT : getGreenSpaceRepository()
activate PLAT

PLAT --> CTRL: greenSpaceRepository
deactivate PLAT

CTRL -> GreenSpaceRepository : greenSpaceTypology()
activate GreenSpaceRepository

GreenSpaceRepository --> CTRL : greenSpaceTypology
deactivate GreenSpaceRepository

CTRL --> UI : getGreenSpaceTypology
deactivate CTRL

UI --> GSM : shows green spaces typology (selected data)
deactivate UI

GSM -> UI : selects one type of green space
activate UI

UI --> GSM : shows all data and requests confirmation
deactivate UI

GSM -> UI : confirms data
activate UI

UI -> CTRL : registerGreenSpace(name, address, area, typology)
activate CTRL

CTRL -> GREENSPACE : registerGreenSpace(name, address, area, typology)
activate GREENSPACE

GREENSPACE -> GREENSPACE : validateEntryAgenda(name)
GREENSPACE -> GREENSPACE : registerGreenSpace

GREENSPACE -> GreenSpaceRepository : greenSpace
deactivate GREENSPACE
activate GreenSpaceRepository
GreenSpaceRepository -> GreenSpaceRepository : add(greenSpace)
GreenSpaceRepository -> CTRL : greenSpace
deactivate GreenSpaceRepository
CTRL -> UI : greenSpace
deactivate CTRL
UI -> GSM : operation success
deactivate UI

@enduml