@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Space\nManager (GSM)" as GSM
participant ":System" as System

activate GSM

    GSM -> System : Asks to postpone a task in the Agenda
    activate System

        System --> GSM : shows a list of all tasks in the Agenda with the status "Planned"
    deactivate System

    GSM -> System : selects a task from the list
    activate System

        System --> GSM : asks for the new date to postpone the selected task

    deactivate System

    GSM -> System : types requested data (date)
    activate System


        System --> GSM : displays operation success
    deactivate System

@enduml