@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) US028

autonumber

actor "Collaborator" as ACTOR
participant ":System" as SYSTEM

activate ACTOR

ACTOR -> SYSTEM: I wish to consult the tasks assigned to me between two dates
activate SYSTEM
SYSTEM --> ACTOR: Requests data (i.e. start date, end date, task status)
deactivate SYSTEM

ACTOR -> SYSTEM: Selects requested data
activate SYSTEM
SYSTEM --> ACTOR: Shows tasks list
deactivate SYSTEM

@enduml
