@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class GSMUI{
}

class AssignTeamToTaskInTheAgendaUI{
+run()
+AssignTeamController()
-requestTask()
-requestTeam()
-submitData(team, task)
}

class AssignTeamController{
+assignTeamController()
+assignTeamToTask()
+listAvailableTeams()
+listUnfinishedTasks()
+getAgenda()
+loadValidEmailServices()
+validEmail()
-getTaskRepository()
-getTeamRepository()
}

class Employee {
+assignTeamToTask(team, task)
}

class Task{
-title : String
-description : String
-startDate : Date
-endDate : Date
-taskStatus : EnumName
-type : String
-greenSpace : GreenSpace
-taskUrgency : EnumName
-assignedTeam : Team
-assignedVehicles : ArrayList<Vehicle>
-taskID : int
-taskPosition : EnumName

+assignTeam()
+setTaskStatus()
+getTaskPosition()
+setEndDate()
+taskOverlap()
-calculateEndDate()

}

class TaskRepository {
+getAgenda()
+updateTask()
+teamAvailability()
+getAllTeamTasks()
+getPlannedTasks()
+getPendingTasks()
+existsTasks()
}

class TeamRepository{
-validateTeam()
+getAllTeams()
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getTaskRepository()
    + getEmployeeRepository()
    + getVehicleRepository()

}

class Tasks {
-ArrayList<Task> tasks
}



GSMUI "1" ..> "1" AssignTeamToTaskInTheAgendaUI

Repositories --> Repositories : instance


AssignTeamToTaskInTheAgendaUI ..> AssignTeamController

AssignTeamController ..> Repositories


Repositories "1"--> "1" TaskRepository
Repositories "1"--> "1" TeamRepository

TaskRepository "1"--> "*" Employee
TeamRepository "1"--> "*" Employee




AssignTeamController ..> Employee

Employee "1" --> "1" Tasks : list tasks
Tasks "1" --> "*" Task


@enduml