@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto
skinparam classAttributeIconSize 0

'left to right direction


class AddNewEntryAgendaUI {

}

class AddNewEntryAgendaController {

    + addEntryAgenda(startDate: String, selectedEntry: ToDoEntry, status: TaskStatus) : void
    + getGreenSpaceList(GreenSpace : List)
    + filterGreenSpacesByManager(GreenSpace : List)
    + getToDoListEntries(ToDoEntry : List)
    + getGreenSpaceRepository() : GreenSpaceRepository
    + getAuthRepository() : AuthRepository
    + getToDoRepository() : ToDoListRepository
    + getAgendaRepository() : AgendaRepository
    + getEmployeeRepository() : GreenSpaceRepository
    + currentUserLogInValidation : boolean
    + matchEmployeeByRole() : Employee

}

class Repositories {
     - Repositories()
     + getInstance() : Repositories
     + getGreenSpaceRepository()
     + getToDoRepository()


}

class GreenSpaceRepository {
    -greenSpaceList : List<GreenSpace>
    +getGreenSpace() : List<GreenSpace>
}

class ToDoListRepository {
    -toDoList : List<ToDoEntry>
    +getToDoList() : List<ToDoEntry>
}

class Agenda {
        -name : String
        -address : String
        -area : double
        -typology : String
        - greenSpaceManager : String

    +registerGreenSpace(name: String, address: String, area: double, typology : String, greenSpaceManager: String) : Optional<GreenSpace>
    +GreenSpace()
    +clone() : GreenSpace
    +compareTo(o:GreenSpace) : int
}





RegisterGreenSpaceController ..> Repositories: repositories
RegisterGreenSpaceController ..> GreenSpaceRepository: greenSpaceRepository
GreenSpaceRepository "1" --> "*" GreenSpace
Repositories "1" --> "1" GreenSpaceRepository
RegisterGreenSpaceUI .> RegisterGreenSpaceController
Repositories -> Repositories : instance

@enduml