@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as ADM
participant ":AddEntryAgendaUI" as UI
participant ":AddEntryAgendaController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository:\nGreenSpaceRepository" as GreenSpaceRepository
participant "employeeRepository:\nEmployeeRepository" as EmployeeRepository
participant "taskRepository:\nTaskRepository" as TaskRepository
participant "task\n:Task" as TAREFA

activate ADM
ref over ADM, UI : This action assumes that the user has already logged in

        ADM -> UI :  asks to add a new entry in the Agenda

        activate UI

            UI -> CTRL : getGreenSpaceList()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getGreenSpaceRepository()
                activate PLAT

                    PLAT --> CTRL: greenSpaceRepository
                deactivate PLAT

                CTRL -> GreenSpaceRepository : getGreenSpaceList()
                activate GreenSpaceRepository

                    GreenSpaceRepository --> CTRL : greenSpaceList
                deactivate GreenSpaceRepository

                CTRL --> UI : greenSpaceList
            deactivate CTRL

            UI --> ADM : shows green spaces to be selected
        deactivate UI

    ADM -> UI : selects green space
    activate UI

UI -> CTRL : getToDoListEntries()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getToDoListRepository()
                activate PLAT

                    PLAT --> CTRL: toDoListRepository
                deactivate PLAT

                CTRL -> TaskRepository : getToDoListEntries()
                activate TaskRepository

                    TaskRepository --> CTRL : toDoListEntries
                deactivate TaskRepository

                CTRL --> UI : toDoListEntries
            deactivate CTRL

            UI --> ADM : shows To-Do List entries (selected data)
        deactivate UI

    ADM -> UI : selects one entry from To-Do List
    activate UI

        UI --> ADM : requests typed data
    deactivate UI

    ADM -> UI : types requested data (startDate)
    activate UI

        UI --> ADM : shows all data and requests confirmation
    deactivate UI

    ADM -> UI : confirms data
    activate UI

        UI -> CTRL : addEntryAgenda(startDate, toDoListEntries)
        activate CTRL


            CTRL -> TAREFA: addEntryAgenda(startDate, toDoListEntries)
            activate TAREFA


                TAREFA -> TAREFA : addEntryAgenda

                TAREFA -> TaskRepository : entryAgenda
                deactivate TAREFA
                activate TaskRepository
                TaskRepository -> TaskRepository : validate(entryAgenda)
                TaskRepository -> CTRL : entryAgenda
                deactivate TaskRepository
                CTRL -> UI : entryAgenda
                deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml