@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as ADM
participant ":AddEntryAgendaUI" as UI
participant ":AddEntryAgendaController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository:\nGreenSpaceRepository" as GreenSpaceRepository
participant "employeeRepository:\nEmployeeRepository" as EmployeeRepository
participant "toDoListRepository:\nToDoListRepository" as ToDoListRepository
participant "agenda\n:Agenda" as TAREFA

activate ADM

        ADM -> UI :  asks to add a new entry in the Agenda

        activate UI

            UI -> CTRL : getGreenSpaceList()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getGreenSpaceRepository()
                activate PLAT

                    PLAT --> CTRL: greenSpaceRepository
                deactivate PLAT

                CTRL -> GreenSpaceRepository : getGreenSpaceList()
                activate GreenSpaceRepository

                    GreenSpaceRepository --> CTRL : greenSpaceList
                deactivate GreenSpaceRepository

                CTRL --> UI : greenSpaceList
            deactivate CTRL

            UI --> ADM : shows green spaces to be selected
        deactivate UI

    ADM -> UI : selects green space
    activate UI

UI -> CTRL : getToDoListEntries()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getToDoListRepository()
                activate PLAT

                    PLAT --> CTRL: toDoListRepository
                deactivate PLAT

                CTRL -> ToDoListRepository : getToDoListEntries()
                activate ToDoListRepository

                    ToDoListRepository --> CTRL : toDoListEntries
                deactivate ToDoListRepository

                CTRL --> UI : toDoListEntries
            deactivate CTRL

            UI --> ADM : shows To-Do List entries (selected data)
        deactivate UI

    ADM -> UI : selects one entry from To-Do List
    activate UI

        UI --> ADM : requests typed data
    deactivate UI

    ADM -> UI : types requested data (startDate)
    activate UI

        UI --> ADM : shows all data and requests confirmation
    deactivate UI

    ADM -> UI : confirms data
    activate UI

        UI -> CTRL : createTask(reference,\ndescription,\ninformalDescription,\ntechnicalDescription,\nduration, cost,\ntaskCategoryDescription)
        activate CTRL

            CTRL -> CTRL : getTaskCategoryByDescription(taskCategoryDescription)
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getTaskCategoryRepository()
                activate PLAT

                    PLAT -> CTRL : taskCategoryRepository
                deactivate PLAT

                CTRL -> TaskCategoryRepository : getTaskCategoryByDescription(taskCategoryDescription)
                activate TaskCategoryRepository

                    TaskCategoryRepository --> CTRL : taskCategory
                deactivate TaskCategoryRepository
                    CTRL --> CTRL : taskCategory
            deactivate CTRL

            |||
            CTRL -> CTRL : getEmployeeFromSession()
            activate CTRL

                CTRL -> _APP: getInstance()
                activate _APP
                    _APP -> CTRL: appSession
                deactivate _APP


                CTRL -> APP: getCurrentSession()
                activate APP

                    APP --> CTRL: currentSession
                deactivate APP

                CTRL -> SESSAO: email = getUserEmail()
                activate SESSAO

                    SESSAO --> CTRL: email
                deactivate SESSAO


                CTRL -> PLAT: getOrganizationRepository(email)
                activate PLAT

                    PLAT --> CTRL: organizationRepository
                deactivate PLAT


                CTRL -> OrganizationRepository: getOrganizationByEmployeeEmail(email)
                activate OrganizationRepository

                    loop [for each organization
                        OrganizationRepository -> ORG : anyEmployeeHasEmail(email)
                        activate ORG

                             ORG --> OrganizationRepository : true/false
                        deactivate ORG
                    end
                    OrganizationRepository --> CTRL : organization
                deactivate OrganizationRepository

                CTRL -> ORG: getEmployeeByEmail(email)
                activate ORG

                    ORG --> CTRL : employee
                deactivate ORG

                CTRL --> CTRL : employee
            deactivate CTRL

            |||
            CTRL -> ORG: createTask(employee, reference, description,\ninformalDescription, technicalDescription,\nduration, cost, , taskCategory, employee)
            activate ORG

                ORG -> TAREFA**: create(employee, reference, description,\ninformalDescription, technicalDescription,\nduration, cost, taskCategory, employee)
                ORG -> ORG: addTask (task)


                activate ORG
                    ORG -> ORG: validateTask(task)
                    activate ORG
                        ORG --> ORG
                    deactivate ORG

                    ORG --> ORG
                deactivate ORG

                ORG --> CTRL : task

            deactivate ORG

            CTRL --> UI: task
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml