@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction
class Employee{
    -name : String
    -birthdate : Date
    -email : String
    -phoneNumber : int
    -admission date : Date
    -taxpayerNumber : String
    -address : String
    -docNumber : String
    -jobTitle : String

    +registerSkill(skillName, skillDescription): Optional<Skill>
    +validateSkill(skill): boolean
    +add(skill): boolean
}

class ToDoEntry{
-greenSpace: GreenSpace
-task: Task
-urgency: String
-startDate: Date
-endDate : Date
}


class AddEntryToDoListController{

}

class AddEntryToDoListUI{

}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getEmployeeRepository(); employeeRepository

}
class EmployeeRepository{


+getEmployee(): Employee

}
class TasksRepository{
 +getTasks(): List<Task>
 +getTodoTasks(): List<Task>
 +getAgendaTasks(): List<Task>
 +getTask(): Task
}
class GreenSpacesRepository{
+getGreenSpaces(): GreenSpace
}

AddEntryToDoListUI .>AddEntryToDoListController

AddEntryToDoListController .> "1" Repositories

Repositories "1" --> "1" Repositories : getInstance()
Repositories "1" --> "1" EmployeeRepository
Repositories "1" --> "1" TasksRepository
Repositories "1" --> "1" GreenSpacesRepository

AddEntryToDoListController ..>Employee

EmployeeRepository "1" --> "1" Employee
TasksRepository "1" --> "1" Employee
GreenSpacesRepository "1" --> "1" Employee

Employee --> ToDoEntry: registers


@enduml