@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class ListGreenSpacesManagedUI{
}

class ListGreenSpacesManagedController{
}

class Employee {
+getGreenSpacesManaged()
}

class GreenSpaces{
-ArrayList<GreenSpace> greenSpaces
}

class GreenSpace{
}


class EmployeeRepository {
}




class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getEmployeeRepository()

}





Repositories --> Repositories : instance


ListGreenSpacesManagedUI ..> ListGreenSpacesManagedController

ListGreenSpacesManagedController ..> Repositories : repositories



Repositories "1"--> "1" EmployeeRepository



EmployeeRepository "1"--> "*" Employee


Employee "1" --> "*"GreenSpaces: list GreenSpaces
GreenSpaces "1" --> "*"GreenSpace


ListGreenSpacesManagedController .> Employee


@enduml