@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) US029

autonumber

actor "Collaborator" as ACTOR
participant ":System" as SYSTEM

activate ACTOR

ACTOR -> SYSTEM: selects a task to complete
activate SYSTEM
    SYSTEM --> ACTOR: requests data(optionalObservations,endDate)
deactivate SYSTEM
ACTOR -> SYSTEM: types requested data
activate SYSTEM
    SYSTEM --> ACTOR : shows all data and requests confirmation
deactivate SYSTEM

ACTOR -> SYSTEM : confirms data

activate SYSTEM
SYSTEM --> ACTOR: displays operation success
deactivate SYSTEM

@enduml
