@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class AssignVehicleToAgendaEntryUI{
}

class AssignVehicleToAgendaEntryController{
+getEmployeeRepository()
+getTaskRepository()
+getVehicleRepository()
+getAvailableTasks()
+getAvailableVehicles(Task taskSelected)
+getTaskAssignedVehicles(Task task)
+assignVehicleToTask(Vehicle vehicle, Task task)
}

class Employee {
+assignVehicleToTask(Vehicle availableVehicle, Task selectedTask)
}

class Task{
}

class TaskRepository {
+getAllAgendaTasksExceptDoneCanceled()
+getVehicleAvaiability(Task taskSelecionada, List<Vehicle> vehicles)
}

class EmployeeRepository {
+getEmployee(): employee
}

class VehicleRepository{
+getVehicles()

}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getTaskRepository()
    + getEmployeeRepository()
    + getVehicleRepository()

}





Repositories --> Repositories : instance


AssignVehicleToAgendaEntryUI ..> AssignVehicleToAgendaEntryController

AssignVehicleToAgendaEntryController ..> Repositories : repositories


Repositories "1"--> "1" TaskRepository
Repositories "1"--> "1" EmployeeRepository
Repositories "1"--> "1" VehicleRepository

TaskRepository "1"--> "*" Employee
EmployeeRepository "1"--> "*" Employee
VehicleRepository "1"--> "*" Employee

Employee "1" --> "*"Task


AssignVehicleToAgendaEntryController ..> Employee


















@enduml